install-python:
	pip3 install requests
# Upgrades gradle version across all projects
upgrade-gradle:
	python3 upgradeGradle.py
# Upgrades makefile scripts
upgrade-makefile-variables:
	python3 upgradeMakefileScripts.py
upgrade-circle-ci:
	python3 upgradeCircleCIScripts.py