services:

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:14.1
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./init-scripts/multiple:/docker-entrypoint-initdb.d/multiple
      - ./init-scripts/multiple/stacos:/docker-entrypoint-initdb.d/multiple/stacos
      - ./init-scripts/multiple/furniture:/docker-entrypoint-initdb.d/multiple/furniture
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=staco:stacos,stacky,furniture
      - POSTGRES_FOLDER_MAPPING=true
    ports:
      - "5432:5432"
    expose:
      - "5432"
