name: PSR Pull Request

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'adopt'

    - name: Build and Test
      run:  mvn clean install jacoco:prepare-agent package jacoco:report
