name: PSR Pull Request

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1
    - name: Set up JDK 21
      uses: actions/setup-java@2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build and Test
      run:  mvn clean install jacoco:prepare-agent package jacoco:report
